- js/pdi-browser.strip.js
- package.json
IEのオーディオ対応のため、内部コンポーネントを更新します。
なし。
> Update internal component

- js/game-driver.strip.js
- js/pdi-browser.strip.js
- package.json
* 'pdi-browser' をv0.7.4に更新
* 'game-driver' をv0.7.1に更新
ありません。
> Use pdi-browser v0.7.4

- CHANGELOG.md
- js/game-driver.strip.js
- js/game-storage.strip.js
- js/pdi-browser.strip.js
- package.json
- akashic-engine@1.12.0 に追従します。
- それに伴い一部内部コンポーネントを更新します。
差分多数ですが実質 package.json の更新のみです。セルフマージします。
なし。
> Make version 0.11.0. Use akashic-engine@1.12.0

- CHANGELOG.md
- package.json
* `akashic-engine@1.12.2` を利用するように
なし
> Make version 0.12.2

- js/developer.js
- js/sandbox.js
> Fix: Use default token

- js/game-driver.strip.js
- js/pdi-browser.strip.js
- package.json
* ~~'akashic-engine' をv0.12.2に更新~~
* 'akashic-engine' をv0.12.4に更新
* 'game-driver' をv0.11.4に更新
* 'pdi-browser' をv0.9.4に更新
なし
> Update internal module and make 0.12.5

- js/pdi-browser.strip.js
- package.json
- akashic-engineを1.12.5に更新します
- pdi-browserを0.10.0に更新します
> Update internal modules and make 0.13.0

- js/developer.js
- js/game-driver.strip.js
- js/pdi-browser.strip.js
- js/sandbox.js
- package.json
掲題どおり。
- akashic-engine@2.0.0 に追従
- `Trigger` の I/F 変更
- `multplyPoint` の廃止
- 内部コンポーネントを更新
自明につきセルフマージします。
> make version 1.0.0-beta.0, use akashic-engine@2.0.0-beta.0

- js/pdi-browser.strip.js
- package.json
> Update internal modules and make 0.13.2

- js/pdi-browser.strip.js
- package.json
> Update internal modules and make 1.0.0-beta.1

- CHANGELOG.md
- js/v1/akashic-engine.js
- js/v2/pdi-browser.strip.js
- package.json
* akashic-engine@2.0.2
* game-driver@1.0.0
* pdi-browser@1.0.1
* akashic-engine@1.12.7
* game-driver@0.11.7
* pdi-browser@0.10.3
> Update internal modules

- CHANGELOG.md
- js/v1/developer.js
- js/v2/developer.js
- package.json
掲題の通りです。javascript部分からarrow functionを削除します。
これは主に互換性を考慮した修正です。
自明につきセルフマージします。
> drop arrow function

- CHANGELOG.md
- js/v1/developer.js
- js/v2/developer.js
- js/v2/game-driver.strip.js
- js/v2/pdi-browser.strip.js
- package.json
akashic-engine@2.0.3 に対応し、内部モジュールを更新します。
自明につきセルフマージします。
> Make version 0.13.12

- CHANGELOG.md
- js/v1/developer.js
- js/v1/sandbox.js
- js/v2/developer.js
- js/v2/sandbox.js
- package.json
内部コンポーネントのAPI廃止に追従します。
内部コンポーネント自体は https://github.com/akashic-games/akashic-sandbox/pull/39 で更新済みです。
- なし
> Update fit to window

- views/game.ect
https://github.com/akashic-games/akashic-cli-export-html/pull/22 と同様の修正を行います。
修正自体は自明のため、セルフマージします。
- なし
> fix swipe on IE and Edge

- package.json
https://github.com/akashic-games/akashic-cli-export-html/pull/31 の変更を akashic-sandbox に適用します。
これにより #49 の内容が publish されます。
> fix publishConfig

- CHANGELOG.md
- engine-src/v2/external/pdi-browser.strip.js
- engine-src/v2/package.json
v2のエンジンモジュールを以下に更新します。
- akashic-engine@2.3.0
- pdi-browser@1.4.0
> Update internal module

- package.json
Apply #53 and publish version 0.13.21
> Make version 0.13.21

- engine-src/v1/js/developer.js
- engine-src/v1/js/sandbox.js
- engine-src/v2/external/game-driver.strip.js
- engine-src/v2/external/pdi-browser.strip.js
- engine-src/v2/js/developer.js
- engine-src/v2/js/sandbox.js
- engine-src/v2/package.json
- views/developer.ect
掲題どおり。内部モジュールを更新し、仕様変更に追従します。
engine-src/v2/ の変更が主眼です。
engine-src/v1/ 以下の変更は、 views/game.ect の変更 (replayLastTime → replayDuration) への追従と、v2系とできるだけ近い形にとどめておくための修正で、動作の変更はありません。
> Update internal modules and follow the changes: game-driver@1.3.0

- CHANGELOG.md
- engine-src/v2/external/pdi-browser.strip.js
- engine-src/v2/external/versions.json
- engine-src/v2/package.json
- package.json
> 内部コンポーネントの更新

- views/developer.ect
セッションパラメータ関連のデバッグツールのUIを調整します。
> update UI for session parameter tool

- .npmrc
- .travis.yml
- CHANGELOG.md
- README.md
- build/updateEngineFiles.js
- css/developer.css
- engine-src/v1/.npmrc
- engine-src/v1/js/developer.js
- engine-src/v2/.npmrc
- engine-src/v2/js/developer.js
- package.json
- src/server/controller/sandboxConfig.ts
- views/developer.ect
- views/script.ect
* スクリプトにおいて `"use strict"` を常に有効に
* デバッグビルドの engine-files を利用するように
* engine-files のローカルでの動作確認方法について追記
> Use engine-files build debug mode & Enable "use strict" mode

- CHANGELOG.md
- engine-src/v1/js/developer.js
- engine-src/v1/js/sandbox.js
- engine-src/v2/js/developer.js
- engine-src/v2/js/sandbox.js
- package.json
- `fit to window` から `default size` へ戻した時にコンテンツの位置がずれる問題を修正。
- グリッドがずれる問題も修正。
> Fix position of content when becomes defaultSize from fixToWindow

- .travis.yml
travis.ymlの対象からnode8を削除し、node12を追加
> Remove node8 from travis.yml and add node12

- build/updateEngineFiles.js
* engineFIles更新スクリプトでv2系取得時はfor_ae2xタグを、v3系取得時はlatestタグを指定するように修正
> engineFIles更新スクリプトをv3のリリースに合わせて修正

- package.json
> fix publish

- .github/workflows/release.yml
syntax error になったので修正します。
実験のためセルフマージします。
> fix syntax in release.yml

- .github/workflows/release.yml
GitHub Actions のリリース処理を https://github.com/akashic-games/action-release に移行したため、その追従です。
> chore(ci): change repo for releasing action

- package-lock.json
- renovate.json
renovate.json を追加します。
- akashic 系の patch 更新の場合は patch version を bump して automerge します
- akashic 系の minor 更新の場合は minor version を bump しますが automerge はしません
- akashic 系以外の更新は、patch, minor 毎に PR をまとめ、 major 更新はそれぞれ PR を作成します 
- メジャー以外で CI が通ったものは automerge します
**動作確認**
Fork した個人リポジトリで akashic-engine のバージョンを下げ作成された PR を確認。
patch: https://github.com/ShinobuTakahashi/akashic-sandbox/pull/40 (automerge 済み)
minor: https://github.com/ShinobuTakahashi/akashic-sandbox/pull/41
> Add renovate.json

- CHANGELOG.md
- package-lock.json
- package.json
- src/server/controller/sandboxConfig.ts
内部で持っていた sandboxConfig の型の使用を辞め、 @akashic/sandbox-configuration を使用するようにします。
> Use sandbox config

- CHANGELOG.md
- engine-src/v1/js/developer.js
- engine-src/v2/js/developer.js
- engine-src/v3/js/developer.js
- package-lock.json
- package.json
- src/client/akashic/meddling/MeddlingDate.ts
- src/client/akashic/meddling/MeddlingMath.ts
- views/developer.ejs
- views/script.ejs
sandbox.config.js の `warn.useDate`, `warn.useMathRandom` の動作を反映し、設定されていた場合にはその設定を優先させます。
- 既存のUI (Akashicコンテンツで使用すべきでない機能が使用された場合警告を出力のチェックボックス) を disabled へ
- sandbox.config.js で設定されているため無効化されているメッセージを表示します
- Math.random のエラーメッセージ修正
- エラーダイアログに警告設定のメッセージ追加
> Support useDate and useMathRandom of sandbox.config.js

- src/server/app.ts
- src/server/tsconfig.json
- typings/extend.express.d.ts
> enable strict on server side

- engine-src/v3/js/developer.js
Akashic Engine V3 利用時、デベロッパーツールのエンティティ位置を矩形で表示する機能が動かなくなっている問題を修正します。
v3.6.0 で利用するようになった `WeakRefKVS#get()` を利用してエンティティ情報を取得します。
- なし
> use WeakRefKVS#get() to get Entity data

- engine-src/v3/js/developer.js
ref: https://github.com/akashic-games/akashic-sandbox/issues/251
> nullなEを使わないように

- renovate.json
renovate で akashic-engine の更新を抑止する
**動作確認**
フォークしたリポジトリで akashic-engine のメジャー更新の PR 出されされない/既にあるPRがクローズされることを確認。
> Suppress akashic-engin updates with renovate.json

- CHANGELOG.md
- engine-src/v3/js/sandbox.js
- package-lock.json
- package.json
- src/client/SandboxScriptAssetV3.ts
- src/server/controller/js.ts
- views/script.ejs
`ScriptAsset#exports` に対応します。
<details>
<summary>クリックで展開</summary>
```json
{
"width": 800,
"height": 450,
"fps": 30,
"main": "./script/main.js",
"assets": {
"main": {
"type": "script",
"path": "script/main.js",
"global": true
},
"exports": {
"type": "script",
"path": "script/exports.js",
"exports": ["variable"],
"global": true
}
},
"moduleMainScripts": {},
"environment": {
"sandbox-runtime": "3"
}
}
```
```js
let variable = 42;
```
```js
module.exports = () => {
const game = g.game;
const scene = new g.Scene({game});
scene.onLoad.addOnce(() => {
const {variable} = require("./exports");
console.log(variable); // 42 が出力されることを確認
});
game.pushScene(scene);
};
```
</details>
> feat: support ScriptAsset#exports
